### ISSUE TITLE
Parrying the fall from the ship when you're first landing causes the cooldown to go into the negatives.

### ISSUE THREAD

**Issue by tairasoul** [VisualError/LethalParrying#2]
As the title says, it appears to break when you parry the fall from the ship during the part where it's landing.
![image](https://github.com/VisualError/LethalParrying/assets/100938045/d1c2f426-d0c1-4e5e-8996-0b7abd0a15f6)

**Comment by tairasoul** [comment]
Just tested it again and it didn't break it this time.
Unsure if it's random, something on my end or very specific timing that breaks it. Logs have no errors.

**Comment by tairasoul** [comment]
https://github.com/VisualError/LethalParrying/assets/100938045/49f5b081-6cac-483f-95d0-d2647aa8e5b6
Here's a video of it happening.
Above commit was testing if uploading a video to a repo would allow it to embed.

**Comment by VisualError** [comment]
Resolved in version 1.0.3
