### ISSUE TITLE
[Suggestion] You already started, so why not become "Lethal Souls"?

### ISSUE THREAD

**Issue by Darkmega18** [VisualError/LethalParrying#3]
**Dodge roll suggestion:** Allow _"directional jumping"_, aka **dodge roll** with parry time included. Costs the equivalent stamina cost of jumping multiplied by a configurable co-efficient (x5 default?).

Applies force to the player in the aimed direction based on their jump but having a lower percentage of stamina reduces the force. If parry is available is invulnerable/parry active for half a second or so.

Configurable if you can roll with twohanded or "over encumbered/in red weight". Activate by either sprinting while sneaking or quick pressing shift.

**Parry Upgrade suggestion:** If damage has an originating entity like parrying something rather than parrying environmental stuff allow the parry to configurably deal damage back or stun the attacking entity briefly as if it's been flashed/stungunned.

**_Optionally_** look into cross compat with lethal progression, allowing parry time and effectiveness to be extended using skill points from it.

**Comment by tairasoul** [comment]
The part about stunning the enemy you parried was already tried, at [line 126](https://github.com/VisualError/LethalParrying/blob/main/Patches/PlayerControllerBPatch.cs#L126)
I think the reason it doesn't work is due to a lack of replication across clients, considering how the stun grenade does it, which is every client runs the StunExplosion function seperately.

**Comment by Darkmega18** [comment]
guess you'll just have to play an invisible but still working stun grenade effect on the player then when successful parry protects the player? owo

"work arounds"

**Comment by tairasoul** [comment]
Looking at the stun grenade's code, that wouldn't work either.
StunExplosion needs to be called, which is called by ExplodeStunGrenade, which is called by Update.
These are all handled on each client, and a valid stun grenade is needed.
As far as I know, there's no way to spawn something without being the host.
This is probably going to end up being handled by [the NetworkHandler](https://github.com/VisualError/LethalParrying/blob/main/Netcode/ParryNetworkHandler.cs) though.

**Comment by Darkmega18** [comment]
oop. well. however you can make it work. is just a suggestion for now.

**Comment by VisualError** [comment]
Stun mechanic has been added

**Comment by Darkmega18** [comment]
I guess not interested in dodge roll for I-framed evasion? or different mod maybe?
